### ISSUE TITLE
 找不到ffmpeg

### ISSUE THREAD

**Issue by daijinqiu** [zhanghuicuc/SimpleVideoEdit#1]
Unable to resolve dependency for ':library@releaseUnitTest/compileClasspath': Could not resolve com.writingminds:FFmpegAndroid:0.3.2.
Open File
Show Details

**Comment by zhanghuicuc** [comment]
似乎是android studio相关的问题
参考https://stackoverflow.com/questions/46949622/android-studio-3-0-unable-to-resolve-dependency-for-appdexoptions-compileclas
